title: Lucas Clemente Vella の Blog
description: Things that I need to write before I die.
url: "https://lvella.github.io"
baseurl: ""
permalink: /:title/

markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
